
nextflow:
  k8s:
    namespace: "nextflow-pcawg"
    volMounts: "nextflow-pv-claim:/mnt/volume/nextflow"

  weblogUrl: "http://elasticsearch-master:9200/nextflow-pcawg/_doc/"

service-info:
  authInstructionsUrl: "https://example.com/auth"
  contactInfoUrl: "https://example.com/contact"
  defaultWorkflowEngineParameters:
    - defaultValue:
      name: "defaultContainer"
      value: "String"
    - defaultValue:
      name: "workflowVersion"
      value: "String"
  supportedFilesystemProtocols:
    - "S3"
    - "SONG"
  supportedWesVersions: "1.0.0"
  workflowEngineVersions:
    nextflow: "19.07.0.5106"
  workflowTypeVersions:
    pcawg-bwa-mem: "0.0.1"
