nextflow:
  k8s:
    namespace: "nextflow-pcawg"
    volMounts:
      - "nextflow-pv-claim:/pod/dir"
    masterUrl: "localhost:8080"
    trustCertificate: false
  weblogUrl: "http://elasticsearch-master:9200/nextflow-pcawg/_doc/"
