nextflow:
  k8s:
    namespace: "nextflow-pcawg"
    volMounts: "nextflow-pv-claim:/mnt/volume/nextflow"
    masterUrl: "localhost:8080"
  weblogUrl: "http://elasticsearch-master:9200/nextflow-pcawg/_doc/"
